panda:
  # Publish all joint states -----------------------------------
  # joint_state_controller:
  #   type: joint_state_controller/JointStateController
  #   publish_rate: 50  

  # Velocity Controllers -----------------------------------------
  # wheel_1_joint_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_1_joint
  #   pid: {p: 100.0, i: 10.0, d: 0.01}

  # wheel_2_joint_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_2_joint
  #   pid: {p: 100.0, i: 10.0, d: 0.01}

  # wheel_3_joint_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_3_joint
  #   pid: {p: 100.0, i: 10.0, d: 0.01}

  # wheel_4_joint_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_4_joint
  #   pid: {p: 100.0, i: 10.0, d: 0.01}
  
  # World velocity controllers
  panda_x_joint_controller:
    type: position_controllers/JointPositionController
    joint: panda_x_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  panda_y_joint_controller:
    type: position_controllers/JointPositionController
    joint: panda_y_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  panda_z_joint_controller:
    type: position_controllers/JointPositionController
    joint: panda_z_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  panda_z_rotation_controller:
    type: position_controllers/JointPositionController
    joint: panda_z_rotation_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}
